language: python
python: "2.7"

before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install python3.4

install:
    - pip install -M tox

before_script:
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - cp .travis.databases.json pymysql/tests/databases.json

script: tox
